# Generated by Django 3.2.5 on 2022-08-25 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('web', models.CharField(max_length=255)),
                ('date_subscribed', models.DateTimeField(default=datetime.datetime(2022, 8, 25, 3, 5, 30, 618806))),
                ('output', models.IntegerField()),
            ],
        ),
    ]
