# Generated by Django 3.2.5 on 2022-08-25 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_subscribed',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 25, 3, 16, 4, 290321)),
        ),
    ]
